WIP: Switch to llm-load-test v2
openshift-psap/topsail pull request #193
Opened 2024-01-31 14:25 UTC by dagrayvid

2024-01-31 15:11 UTC, kpouget commented on projects/kserve/testing/config.yaml
> +    tests.e2e.llm_load_test.: [8, 16, 32]
`concurrency` is missing here

2024-02-21 10:16 UTC, kpouget requested changes
I made a few minor comments
we'll have to run the tests (single and multi model), and the kserve `visualizations` [parser](https://github.com/openshift-psap/topsail/blob/main/projects/kserve/visualizations/kserve-llm/store/parsers.py#L152) will have to be updated. Maybe the plotting files as well, as I think I currently store untouched the llm-load-test output.

Could you also try to move `subprojects/llm-load-test` into `projects/llm-load-test/llm_load_test`? it didn't work right away when I did the refactoring with the `projects` directory, because Prow couldn't build the image. I didn't go in depth into the issue.

2024-02-21 10:16 UTC, kpouget commented on .gitmodules
> +	branch = main
I'm not sure if this changes the fact that `subprojects/llm-load-test` is pinned to a particular commit of `openshift-psap/llm-load-test` or not?
(I'd like to keep the pinning)

2024-02-21 10:16 UTC, kpouget commented on projects/llm_load_test/roles/llm_load_test_run/tasks/main.yml
> +      cat {{ artifact_extra_logs_dir }}/output/outpout.json | grep . --quiet
```suggestion
      cat {{ artifact_extra_logs_dir }}/output/output.json | grep . --quiet
```

2024-02-21 10:16 UTC, kpouget commented on projects/kserve/testing/test_e2e.py
> +        concurrency=llm_config["concurrency"],
I understand that no proto is required anymore with v2,
could you remove the code generating them in this file, as well as the proto files?
(we'll keep the roles, they might be useful again in the future, who knows)

2024-02-22 21:47 UTC, dagrayvid commented
/test rhoai-light kserve quick

2024-02-23 17:40 UTC, dagrayvid commented
/test rhoai-light kserve quick

2024-02-23 19:59 UTC, dagrayvid commented
/test rhoai-light kserve quick

2024-02-23 20:58 UTC, dagrayvid commented
Okay, this last test succeeded to the extent that we want, we got [output from llm-load-test-v2](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/193/pull-ci-openshift-psap-topsail-main-rhoai-light/1761118573322833920/artifacts/light/test/artifacts/000__local_ci__run_multi_e2e_perf_test/artifacts/ci-pod-0/001__flan-t5-small-cpu/006__llm_load_test__run/output/output.json), we just need to disable the results parsing for now.

2024-02-23 21:27 UTC, dagrayvid commented
/test rhoai-light kserve quick

2024-02-23 22:37 UTC, dagrayvid commented
@kpouget test is green

2024-02-24 10:23 UTC, kpouget commented
thanks @dagrayvid, looks good, I'll merge it.

The visualization (now disabled) fails because of [this error](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/193/pull-ci-openshift-psap-topsail-main-rhoai-light/1761118573322833920/artifacts/light/test/artifacts/003__plots/000__projects.kserve.visualizations.kserve-llm_plots/0_matbench_parse.log).

Here is [a sample](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/193/pull-ci-openshift-psap-topsail-main-rhoai-light/1761118573322833920/artifacts/light/test/artifacts/000__local_ci__run_multi_e2e_perf_test/artifacts/ci-pod-0/001__flan-t5-small-cpu/006__llm_load_test__run/output/output.json) of the next output file of `llm-load-test`.

2024-02-24 10:23 UTC, kpouget approved these changes

2024-02-24 10:24 UTC, merged