WIP: Add Hunter as a Regression Indicator
openshift-psap/topsail pull request #200
Opened 2024-02-13 19:42 UTC by drewrip

2024-02-13 19:45 UTC, drewrip commented
/test rhoai-plot notebooks https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/195/pull-ci-openshift-psap-topsail-main-rhoai-light/1753099883524395008/artifacts/light/test/artifacts/002__sutest_notebooks__benchmark_performance/
/var matbench.workload=rhods-notebooks-performance
/var matbench.config_file=single_notebook_perf.yaml
/var matbench.lts.opensearch.index=regression-test.rhoai-notebooks-performance
/var matbench.lts.opensearch.upload=false

2024-02-13 20:18 UTC, drewrip commented
/test rhoai-plot notebooks https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/195/pull-ci-openshift-psap-topsail-main-rhoai-light/1753099883524395008/artifacts/light/test/artifacts/002__sutest_notebooks__benchmark_performance/
/var matbench.workload=rhods-notebooks-performance
/var matbench.config_file=single_notebook_perf.yaml
/var matbench.lts.opensearch.index=regression-test.rhoai-notebooks-performance
/var matbench.lts.opensearch.upload=false

2024-02-13 20:44 UTC, drewrip commented
/test rhoai-plot notebooks https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/195/pull-ci-openshift-psap-topsail-main-rhoai-light/1753099883524395008/artifacts/light/test/artifacts/002__sutest_notebooks__benchmark_performance/
/var matbench.workload=rhods-notebooks-performance
/var matbench.config_file=single_notebook_perf.yaml
/var matbench.lts.opensearch.index=regression-test.rhoai-notebooks-performance
/var matbench.lts.opensearch.upload=false

2024-02-13 22:00 UTC, drewrip commented
[regression analysis results](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/200/pull-ci-openshift-psap-topsail-main-rhoai-plot/1757506068025446400/artifacts/plot/test/artifacts/report_02_report:%20LTS%20Documentation.html) successfully generated using hunter

2024-02-21 09:56 UTC, kpouget requested changes
thanks @drewrip , looks quite good, just a few nits to change

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/testing/generate_matrix-benchmarking.sh
> +		fi
I'm not sure why you duplicated this block? 🤔 
I think the LTS payload shouldn't change between the first call to `parse --output-lts` and now 🤔

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/testing/generate_matrix-benchmarking.sh
in this file, could you revert the indentation to 4 spaces, and add the few empty lines back? (or are these empty lines inconsistent with the rest of the file? 🤔 )

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/testing/generate_matrix-benchmarking.sh
> +			tee >"$ARTIFACT_DIR/${step_idx}_matbench_download_lts.log"; then
not sure why you changed this,
I like *not* to have the `|`, `|&` or `||` at the end of the line, the idea is to keep important information/operators at the beginning of the line, as it's critical to understand the relationship between the different lines

same for the `then`, if the if condition has multiple lines, I move the `then` to a dedicated line, to clearly distinguish the condition from the `if` statement


```
if very long condition; then
    first statement
```

```
if long condition number 1 &&
    long condition number 2; then
    first statement
```
in these ^^^, if you hide the last ~10 chars, you can't distinguish the conditions from the statements
```
if long condition 1 \
   && long condition 2;
then
    first statement
```
with this, you have 2 ways to distinguish them

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/testing/generate_matrix-benchmarking.sh
> +			tee >"$ARTIFACT_DIR/${step_idx}_matbench_analyze_lts.log" ||
```suggestion
			tee > "$ARTIFACT_DIR/${step_idx}_matbench_analyze_lts.log" ||
```
I try to always keep a space before/after the `>` (except if redirecting into a file description, like `>&2`), let's avoid changing it here

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/visualizations/rhods-notebooks-performance/store/parsers.py
> +        logging.info(f"{regression_results_file} does not exist, no new regression results found.")
can you remove this line (or turn it into a `debug` call)?
or perhaps move it after the `return None` and turn it positive

as it is (from my code), it's too chatty and does not help much

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/visualizations/rhods-notebooks-performance/store/parsers.py
> +    outside_test_env = os.getenv("OUTSIDE_TEST_ENV")
hum, I see what happened. Can you remove this line?

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/visualizations/rhods-notebooks-performance/store/parsers.py
> +    if test_config.get("export_artifacts.enabled") and not outside_test_env:
can you turn this into:
```suggestion
    if test_config.get("export_artifacts.enabled") and from_env.test.ci_engine is not None:
```

and maybe above, replace:
```
if ansible_env.get("PERFLAB_CI") == "true":
by
if from_env.test.ci_engine == "PERFLAB_CI"
and same above:
if from_env.test.ci_engine == "OPENSHIFT_CI"
```

2024-02-21 09:56 UTC, kpouget commented on projects/notebooks/testing/generate_matrix-benchmarking.sh
> +		fi
hum, got it. Can you add a comment:
```
# regenerate the LTS payload to capture the regression analyses results
```
and we'll have to update [the Python file](https://github.com/openshift-psap/topsail/blob/main/topsail/testing/visualize.py#L373) as well, eventually

2024-09-10 20:13 UTC, kpouget commented
closing as outdated

2024-09-10 20:13 UTC, closed without merging